// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
	message: "Hello from Timoni"
	image: {
		repository: "nginx"
		digest:     ""
		tag:        "latest"
	}
	replicas: 1
	service: {
		port: 80
	}
	test: image: {
		repository: "cgr.dev/chainguard/curl"
		digest:     ""
		tag:        "latest"
	}
}
